{{- $enabled := include "commerce-app-v2.configs.spring-boot.application.enabled" . | include "strToBool" }}
{{- if $enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commerce-app-v2.resourceName" (merge (dict "resourceNameInfix" "-spring-boot-app-config") .) }}
  labels:
    {{- include "commerce-app-v2.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- include "commerce-app-v2.configFileContent" (merge (dict "configType" "application" "appFrameworkType" "spring-boot" "originalConfigFileExtension" ".yaml") .)  | nindent 4 }}
{{- end }}
