{{- $enabled := include "commerce-app-v2.configs.standard.crypto.enabled" . | include "strToBool" }}
{{- if $enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commerce-app-v2.resourceName" (merge (dict "resourceNameInfix" "-crypto-config") .) }}
  labels:
    {{- include "commerce-app-v2.labels" . | nindent 4 }}
data:
  crypto_config.json: |
    {
      "mode": "KMS",
      "product": "ecomm",
      "preferredRegion": "{{ required ".Values.awsRegion required!" .Values.awsRegion }}",
      "regionMap": {{ required ".Values.configs.standard.crypto.kmsKeyArnRegionMap required!" .Values.configs.standard.crypto.kmsKeyArnRegionMap }}
    }
{{- end }}
