{{- $enabled := include "commerce-app-v2.configs.standard.crypto.enabled" . | include "strToBool" }}
{{- if $enabled }}
{{ $awsRegion := required ".Values.awsRegion required!" .Values.awsRegion }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "commerce-app-v2.resourceName" (merge (dict "resourceNameInfix" "-crypto-config") .) }}
  labels:
    {{- include "commerce-app-v2.labels" . | nindent 4 }}
spec:
  backendType: systemManager
  region: {{ required ".Values.awsRegion required!" .Values.awsRegion }}
  data:
    - key: /AdminParams/Team/KMSKeyArn
      name: kmsKeyArn
  template:
    stringData:
      crypto_config.json: |
        {
          "mode": "KMS",
          "product": "ecomm",
          "preferredRegion": "{{ $awsRegion }}",
          "regionMap": {
            "{{ $awsRegion }}": "<%= data.kmsKeyArn %>"
          },
          "regionMapTest": {{ .Values.configs.standard.crypto.kmsKeyArns | toJson }}
        }
{{- end }}
