{{- $enabled := include "commerce-app-v2.configs.vertx.options.enabled" . | include "strToBool" }}
{{- if $enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commerce-app-v2.resourceName" (merge (dict "resourceNameInfix" "-vertx-options") .) }}
  labels:
    {{- include "commerce-app-v2.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- include "commerce-app-v2.configFileContent" (merge (dict "configType" "vertx-options" "appFrameworkType" "vertx" "originalConfigFileExtension" ".yaml") .) | fromYaml | toJson | b64enc | nindent 4 }}
{{- end }}
