{{- if eq (required ".Values.app.frameworkType required!" .Values.app.frameworkType) "springboot" }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "commerce-app-v2.resourceName" (merge (dict "resourceNameInfix" "-wildcard-cert") .) }}
  labels:
    {{- include "commerce-app-v2.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Values.secret.certName }}
      name: {{ .Values.secret.certName }}
    - key: {{ .Values.secret.certPass }}
      name: {{ .Values.secret.certPass }}
{{- end }}
